[package]
name = "tplay"
version = "0.3.0"
edition = "2021"
authors = ["Max Curzi <massimiliano.curzi@gmail.com>"]
description = "A terminal based media player that visualizes images and videos as ASCII art."
repository = "https://www.github.com/maxcurzi/tplay"
license = "MIT"
readme = "README.md"
keywords = ["media-player", "ASCII-art", "terminal", "youtube", "video"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::video",
    "multimedia::images",
]
exclude = [
    ".github/",
    ".vscode/",
    ".gitignore",
    "Cargo.lock",
    "Cargo.toml.orig",
    "Makefile.toml",
]
default-run = "tplay"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
crossterm = "0.26.1"
gif = "0.12.0"
image = "0.24.6"
opencv = "0.80"
thiserror = "1.0.40"
fast_image_resize = "2.7.0"
youtube_dl = "0.8.0"
tempfile = "3.5.0"
url = "2.3.1"
serde_json = "1.0.96"
ffmpeg-next = "6.0.0"
crossbeam-channel = "0.5.8"
num = "0.4.0"
either = "1.8.1"
#libmpv = "2.0.1" # Doesn't work with mpv 0.35
libmpv-sirno="2.0.2-fork.1" # Fork to work with mpv 0.35, but it doesn't work with mpv 0.34

[dev-dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }

[[bin]]
name = "tplay"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "Max Curzi <massimiliano.curzi@gmail.com>"
depends = "libopencv-dev clang libclang-dev libmpv1 libmpv-dev ffmpeg libavfilter-dev libavdevice-dev"
